// <auto-generated />
using HealthFoodAPI.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace HealthFoodAPI.Migrations
{
    [DbContext(typeof(HealthFoodAPIContext))]
    [Migration("20181121234552_test")]
    partial class test
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.4-rtm-31024");

            modelBuilder.Entity("HealthFoodAPI.Models.RecipesItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Category");

                    b.Property<string>("CookTime");

                    b.Property<string>("Description");

                    b.Property<string>("Dietary");

                    b.Property<string>("Height");

                    b.Property<string>("Image");

                    b.Property<string>("Link");

                    b.Property<string>("PostName");

                    b.Property<string>("Size");

                    b.Property<string>("Subcategory");

                    b.Property<string>("TimeUnit");

                    b.Property<string>("Title");

                    b.Property<string>("Uploaded");

                    b.Property<string>("Width");

                    b.HasKey("Id");

                    b.ToTable("RecipesItem");
                });
#pragma warning restore 612, 618
        }
    }
}
